# This workflow to help you automate your building process

name: Build & Deploy APK

# Controls when the workflow will run
on:
  push:
    branches: [ main ]



jobs:
  builds:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
         java-version: 17
        
      - name: Build Gradle
        run: ./gradlew build
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: viniviaSDK
          path: viniviaSDK/build/outputs/apk/debug/viniviaSDK-debug.apk